export declare function verbose(...args: any[]): void;
export declare function log(...args: any[]): void;
export declare function info(...args: any[]): void;
export declare function warn(...args: any[]): void;
export declare function error(...args: any[]): void;
export declare function ok(...args: any[]): void;
export declare function indent(amount?: number): void;
export declare function unindent(amount?: number): void;
export declare function divider(text: string, divider?: string): void;
export declare function timestamp(): void;
export declare function logf(format: string, ...args: any[]): void;
export declare function line(count?: number): void;
export declare function addFormat(name: string, format: string): void;
export declare function addColor(name: string, color: string): void;
